
spring:
  jpa:
    database: POSTGRESQL
  datasource:
      platform: postgres
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/questionnaire
      username: postgres
      password: postgres
  jmx:
      enabled: false      
  #下記がないと、ジョブを管理するメタテーブルデータが作成されない(バッチ処理)
  batch: 
    initialize-schema: always  
